imports:
  - { resource: "config/parameters.yml" }

services:

  curriculum.table_writer_factory:
    class: Services\TableWriterFactory

  curriculum.header:
    class: Curriculum\HeaderWriter
    arguments:
      - "%header%"
      - "%title%"
      - "%picture%"

  curriculum.left_pane:
    class: Curriculum\PaneWriter
    arguments:
      - "%left_pane%"
      - "@curriculum.table_writer_factory"

  curriculum.right_pane:
    class: Curriculum\PaneWriter
    arguments:
      - "%right_pane%"
      - "@curriculum.table_writer_factory"

  curriculum.renderer:
    class: Curriculum\Renderer
    arguments:
      - "@curriculum.header"
      - [
          "@curriculum.left_pane",
          "@curriculum.right_pane"
        ]
      - '%file_name%'
    calls:
      - method: render
      - method: renderAndSave
